name: CI-CD-PIpeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover -s tests

    - name: Deploy to Heroku
      if: success()
      run: |
        echo "Deploying to Heroku..."
        curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
        heroku container:login
        heroku container:push web -a flask-mypy
        heroku container:release web -a flask-mypy
        heroku_app_name: "flask-mypy"
        heroku_email: "thoshnadevice@gmail.com"


