name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover -s tests

    - name: Deploy to Heroku
      if: success()
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: "flask-mypy"
        HEROKU_EMAIL: "thoshnadevice@gmail.com"
      run: |
        heroku login --email $HEROKU_EMAIL --password $HEROKU_API_KEY
        git push https://git.heroku.com/$HEROKU_APP_NAME.git HEAD:main
